=== gs1/GS1DigitalLicenses/schemas/custom_shipment.json
{
  "$id": "GS1-Data-Schema",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "version": "1.0.0",
  "title": "DataCredential",
  "description": "The product data credential is the Verifiable Credential that is shared with parties interested in the basic information associated with a GS1 ID Key.",
  "type": "object",
  "$defs": {
    "GS1DigitalLink": {
      "title": "GS1 Digital Link",
      "type": "string",
      "format": "uri",
      "pattern": "^https?:(\\/\\/((([^\\/?#]*)@)?([^\\/?#:]*)(:([^\\/?#]*))?))?([^?#]*)(((\\/(01|8006|8013|8010|414|417|8017|8018|255|00|253|401|402|8003|8004)\\/)(\\d{4}[^\\/]+)(\\/[^/]+\\/[^/]+)?\\/?(\\?([^?\\n]*))?(#([^\\n]*))?))$"
    },
    "DID": {
      "title": "Decentralized Identifier (DID)",
      "type": "string",
      "format": "uri",
      "pattern": "^did:[a-z0-9]+:(?:[A-Za-z0-9._-]|%[0-9A-Fa-f]{2})+(?::(?:[A-Za-z0-9._-]|%[0-9A-Fa-f]{2})+)*$"
    },
    "Issuer": {
      "title": "Issuer",
      "description": "The issuer of the credential",
      "type": "object",
      "properties": {
        "id": {
          "title": "Issuer Identifier",
          "type": "string",
          "format": "uri"
        },
        "name": {
          "title": "Issuer Name",
          "type": "string"
        }
      },
      "required": [
        "id"
      ]
    },
    "RenderMethod": {
      "type": "object",
      "description": "Rendering support",
      "properties": {
        "id": {
          "title": "Render Method Id",
          "type": "string",
          "format": "uri"
        },
        "type": {
          "type": "string",
          "const": "TemplateRenderMethod"
        },
        "name": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "type"
      ]
    },
    "CredentialSchema": {
      "type": "object",
      "properties": {
        "id": {
          "title": "Credential Schema Identifier",
          "type": "string",
          "format": "uri"
        },
        "type": {
          "title": "Credential Schema Type",
          "const": "JsonSchema"
        }
      },
      "required": [
        "id",
        "type"
      ]
    },
    "CredentialStatus": {
      "type": "object",
      "description": "Revocation supported.",
      "properties": {
        "id": {
          "title": "Credential Status",
          "type": "string",
          "format": "uri"
        },
        "type": {
          "type": "string",
          "const": "BitstringStatusListEntry"
        },
        "statusPurpose": {
          "type": "string",
          "const": "revocation"
        },
        "statusListIndex": {
          "type": "string"
        },
        "statusSize": {
          "type": "number"
        },
        "statusListCredential": {
          "type": "string",
          "format": "uri"
        },
        "statusMessage": {
          "type": "array",
          "readOnly": true,
          "items": {
            "type": "object",
            "properties": {
              "status": {
                "type": "string",
                "enum": [
                  "0x0",
                  "0x1"
                ]
              },
              "message": {
                "type": "string",
                "enum": [
                  "valid",
                  "revoked"
                ]
              }
            },
            "required": [
              "status",
              "message"
            ]
          }
        }
      },
      "required": [
        "id",
        "type",
        "statusPurpose",
        "statusListIndex",
        "statusListCredential"
      ]
    },
    "Organization": {
      "title": "An Organization is any legal or physical entity involved at any point in any supply chain and upon which there is a need to retrieve predefined information. An Organization is uniquely identified by a Global Location Number (GLN).",
      "type": "object",
      "properties": {
        "gs1:partyGLN": {
          "title": "13-digit GLN that is being used to identify a legal entity or function. If gs1:glnType is present, gs1:partyGLN SHALL only be used when gs1:GLN_TypeCode includes LEGAL_ENTITY and/or FUNCTION",
          "type": "string",
          "pattern": "^\\d{13}$"
        },
        "gs1:organizationName": {
          "title": "The name of the organization expressed in text.",
          "type": "string"
        }
      },
      "required": [
        "gs1:partyGLN",
        "gs1:organizationName"
      ]
    },
    "ValidFrom": {
      "description": "Date from which the credential is to be considered valid.",
      "type": "string",
      "format": "date-time"
    }
  },
  "properties": {
    "@context": {
      "type": "array",
      "items": {
        "oneOf": [
          {
            "type": "string",
            "format": "uri"
          },
          {
            "type": "object",
            "minProperties": 1,
            "additionalProperties": true
          }
        ]
      },
      "allOf": [
        {
          "contains": {
            "const": "https://www.w3.org/ns/credentials/v2"
          }
        },
        {
          "contains": {
            "const": "https://ref.gs1.org/gs1/vc/declaration-context"
          }
        },
        {
          "contains": {
            "const": "https://ref.gs1.org/gs1/vc/product-context"
          }
        }
      ]
    },
    "id": {
      "type": "string",
      "format": "uri"
    },
    "type": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "allOf": [
        {
          "contains": {
            "const": "VerifiableCredential"
          }
        },
        {
          "contains": {
            "const": "DataCredential"
          }
        },
        {
          "contains": {
            "const": "ShipmentCredential"
          }
        }
      ]
    },
    "issuer": {
      "$ref": "#/$defs/Issuer"
    },
    "validFrom": {
      "$ref": "#/$defs/ValidFrom"
    },
    "name": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "credentialSubject": {
      "type": "object",
      "properties": {
        "id": {
          "$ref": "#/$defs/GS1DigitalLink"
        },
        "sameAs": {
          "$ref": "#/$defs/DID"
        },
        "keyAuthorization": {
          "title": "Reference to a credential that authorizes the issuer to declare data for the credential subject (the key). Normally, this is the key credential itself, in which case the issuer of this and the key credential must be the same. For data that is declared by other parties on behalf of the issuer of the key credential, an authorization credential may be provided instead. In some circumstances, where the issuer of the data declaration is entirely independent, the key authorization may be entirely outside of the GS1 system (e.g., aproof-of-purchase Verifiable Credential for a product review).",
          "type": "string",
          "format": "uri"
        },
        "gs1:hasShippedFrom": {
          "type": "object",
          "properties": {
            "type": {
              "const": "gs1:Place"
            },
            "gs1:gln": {
              "type": "string",
              "pattern": "^[0-9]{13}$"
            }
          },
          "required": [
            "type",
            "gs1:gln"
          ],
          "additionalProperties": false
        },
        "gs1:hasShippedTo": {
          "type": "object",
          "properties": {
            "type": {
              "const": "gs1:Place"
            },
            "gs1:gln": {
              "type": "string",
              "pattern": "^[0-9]{13}$"
            }
          },
          "required": [
            "type",
            "gs1:gln"
          ],
          "additionalProperties": false
        },
        "gs1:shipmentDate": {
          "type": "object",
          "properties": {
            "type": {
              "const": "xsd:dateTime"
            },
            "value": {
              "type": "string",
              "format": "date-time"
            }
          }
        }
      },
      "required": [
        "id",
        "type",
        "gs1:hasShippedFrom",
        "gs1:hasShippedTo",
        "gs1:shipmentDate"
      ]
    },
    "credentialSchema": {
      "oneOf": [
        {
          "$ref": "#/$defs/CredentialSchema"
        },
        {
          "type": "array",
          "items": {
            "$ref": "#/$defs/CredentialSchema"
          },
          "minItems": 1
        }
      ]
    },
    "credentialStatus": {
      "oneOf": [
        {
          "$ref": "#/$defs/CredentialStatus"
        },
        {
          "type": "array",
          "items": {
            "$ref": "#/$defs/CredentialStatus"
          },
          "minItems": 1
        }
      ]
    },
    "renderMethod": {
      "oneOf": [
        {
          "$ref": "#/$defs/RenderMethod"
        },
        {
          "type": "array",
          "items": {
            "$ref": "#/$defs/RenderMethod"
          },
          "minItems": 1
        }
      ]
    }
  },
  "required": [
    "@context",
    "id",
    "type",
    "issuer",
    "credentialSubject",
    "credentialSchema"
  ]
}

=== gs1/GS1DigitalLicenses/jsons/sscc-data-credential-sample.json
{
  "@context": [
    "https://www.w3.org/ns/credentials/v2",
    "https://ref.gs1.org/gs1/vc/declaration-context",
    "https://ref.gs1.org/gs1/vc/product-context",
    {
      "gs1": "https://gs1.org/voc/",
      "schema": "https://schema.org/",
      "xsd": "http://www.w3.org/2001/XMLSchema#"
    }
  ],
  "type": [
    "VerifiableCredential",
    "DataCredential",
    "ShipmentCredential"
  ],
  "issuer": {
    "id": "did:web:gs1.github.io:GS1DigitalLicenses:dids:fake_mc_did",
    "name": "Healthy Tots"
  },
  "id": "https://gs1.github.io/GS1DigitalLicenses/samples/sscc-data-credential-sample.jwt",
  "validFrom": "2024-01-25T12:30:00.000Z",
  "name": "Custom Shipment Data Credential",
  "description": "THIS GS1 DIGITAL LICENSE CREDENTIAL IS FOR TESTING PURPOSES ONLY. The data credential is the Verifiable Credential that is shared with parties interested in the basic information associated with GS1 ID Key.",
  "credentialSubject": {
  "id": "https://id.gs1.org/00/08101595500000101",
  "keyAuthorization": "https://gs1.github.io/GS1DigitalLicenses/samples/sscc-key-credential-sample.jwt",
  "type": "gs1:Shipment",

    "gs1:hasShippedFrom": {
      "type": "gs1:Place",
      "gs1:gln": "9506000000001"
    },
    "gs1:hasShippedTo": {
      "type": "gs1:Place",
      "gs1:gln": "9506000000002"
    },

    "gs1:shipmentDate": {
      "value": "2025-07-30T08:00:00Z",
      "type": "xsd:dateTime"
    }
  },
  "credentialSchema": {
    "id": "https://gs1.github.io/GS1DigitalLicenses/schemas/custom_shipment.json",
    "type": "JsonSchema"
  },
  "credentialStatus": {
    "id": "https://gs1.github.io/GS1DigitalLicenses/status/mc_status_list.jwt#33412",
    "type": "BitstringStatusListEntry",
    "statusPurpose": "revocation",
    "statusListIndex": "33412",
    "statusListCredential": "https://gs1.github.io/GS1DigitalLicenses/status/mc_status_list.jwt"
  }
}
